"""
de_elections_address_lookup.py
-------------------------------
Generated by AI (Claude).

MIT License — Copyright (c) 2026 Pat Hennessy
See LICENSE file for full text.

Reads a CSV with an address column, geocodes each address via the Delaware
FirstMap locator, then performs point-in-polygon queries to retrieve:

  - State Senate district & senator
  - State House district & representative
  - County officials (executive, council/levy court, sheriff, clerk of peace,
    register of wills, recorder of deeds)
  - Wilmington City Council district & members (Wilmington addresses only)
  - School board district & board members

County administrative structures vary:
  - New Castle: County Executive + County Council (with President)
  - Kent:       Levy Court Commissioners (president identified by Title field)
  - Sussex:     County Council (no County Executive)

Usage:
    python de_elections_address_lookup.py input.csv --output output.csv
    python de_elections_address_lookup.py input.csv --address-col "Property Address" --output output.csv

Requirements:
    pip install requests
"""

import argparse
import csv
import json
import logging
import sys
import time
from typing import Optional

import requests

# ---------------------------------------------------------------------------
# API endpoints
# ---------------------------------------------------------------------------

GEOCODE_URL = (
    "https://enterprise.firstmap.delaware.gov/arcgis/rest/services/"
    "Location/Delaware_FirstMap_Locator/GeocodeServer/findAddressCandidates"
)
FEATURE_SERVER_BASE = (
    "https://enterprise.firstmap.delaware.gov/arcgis/rest/services/"
    "Boundaries/DE_Political_Boundaries/FeatureServer"
)
COUNTY_OFFICIALS_URL = (
    "https://services1.arcgis.com/bFDgLqS5IyUBQLAd/arcgis/rest/services/"
    "County_Officials_gdb/FeatureServer/0"
)

# ---------------------------------------------------------------------------
# Output column order
# ---------------------------------------------------------------------------

OUTPUT_COLS = [
    # Geocode
    "geocoded_address",
    "geocode_score",
    # State legislators
    "senate_district",
    "senator",
    "senator_url",
    "house_district",
    "representative",
    "representative_url",
    # County officials
    "county",
    "county_district",
    "county_executive",           # New Castle only
    "county_council_president",   # New Castle; Kent Levy Court president
    "county_council_member",      # District council member / levy court commissioner
    "county_sheriff",
    "clerk_of_peace",
    "register_of_wills",
    "recorder_of_deeds",
    # Wilmington City Council (Layer 5 — non-Wilmington addresses will be empty)
    "wilm_city_council_district",
    "wilm_council_president",
    "wilm_council_member",
    "wilm_council_at_large",
    # School board (Layer 4 — all data is inline)
    "school_district",
    "school_board_district",
    "school_board_members_district",   # semicolon-separated district seat holders
    "school_board_members_at_large",   # semicolon-separated at-large members
]

logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s  %(message)s",
    stream=sys.stderr,
)
log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# API helpers
# ---------------------------------------------------------------------------

def geocode_address(session: requests.Session, address: str) -> Optional[dict]:
    """Return the top geocode candidate dict, or None."""
    params = {
        "SingleLine": address,
        "maxLocations": 1,
        "outSR": json.dumps({"wkid": 102100}),
        "f": "json",
    }
    try:
        resp = session.get(GEOCODE_URL, params=params, timeout=15)
        resp.raise_for_status()
        data = resp.json()
    except Exception as exc:
        log.warning("Geocode failed for '%s': %s", address, exc)
        return None

    candidates = data.get("candidates", [])
    if not candidates:
        log.warning("No geocode match for: %s", address)
        return None
    return candidates[0]


def query_political_layer(
    session: requests.Session,
    layer_id: int,
    x: float,
    y: float,
    fields: list,
) -> Optional[dict]:
    """Point-in-polygon query against DE_Political_Boundaries FeatureServer."""
    params = {
        "f": "json",
        "geometry": json.dumps({"x": x, "y": y}),
        "geometryType": "esriGeometryPoint",
        "inSR": "102100",
        "spatialRel": "esriSpatialRelIntersects",
        "outFields": ",".join(fields),
        "returnGeometry": "false",
        "resultRecordCount": 500,
        "where": "1=1",
    }
    url = f"{FEATURE_SERVER_BASE}/{layer_id}/query"
    try:
        resp = session.get(url, params=params, timeout=15)
        resp.raise_for_status()
        data = resp.json()
    except Exception as exc:
        log.warning("Layer %d query failed: %s", layer_id, exc)
        return None

    if data.get("exceededTransferLimit") and not data.get("features"):
        log.warning("Layer %d returned exceededTransferLimit with 0 features", layer_id)
        return None

    features = data.get("features", [])
    return features[0].get("attributes", {}) if features else None


def query_county_officials(
    session: requests.Session,
    x: float,
    y: float,
) -> tuple[Optional[str], Optional[str], list]:
    """
    Two-step county officials lookup.
    Returns (county_name, district_label, officials_list).
    officials_list is [{office, name, title}, ...].
    """
    # Step 1 — spatial query → OBJECTID + labels
    params1 = {
        "f": "json",
        "geometry": json.dumps({"x": x, "y": y}),
        "geometryType": "esriGeometryPoint",
        "inSR": "102100",
        "spatialRel": "esriSpatialRelIntersects",
        "outFields": "OBJECTID,COUNTY,DISTRICT",
        "returnGeometry": "false",
        "resultRecordCount": 500,
    }
    try:
        resp = session.get(f"{COUNTY_OFFICIALS_URL}/query", params=params1, timeout=15)
        resp.raise_for_status()
        data1 = resp.json()
    except Exception as exc:
        log.warning("County officials spatial query failed: %s", exc)
        return None, None, []

    features = data1.get("features", [])
    if not features:
        log.warning("No county officials district found for (%.0f, %.0f)", x, y)
        return None, None, []

    attrs1 = features[0]["attributes"]
    oid = attrs1.get("OBJECTID")
    county = str(attrs1.get("COUNTY") or "")
    district = str(attrs1.get("DISTRICT") or "")

    if oid is None:
        return county, district, []

    # Step 2 — related records → official roster
    params2 = {
        "f": "json",
        "objectIds": str(oid),
        "outFields": "County,Office,Name,Title",
        "relationshipId": 0,
        "returnGeometry": "false",
    }
    try:
        resp = session.get(
            f"{COUNTY_OFFICIALS_URL}/queryRelatedRecords", params=params2, timeout=15
        )
        resp.raise_for_status()
        data2 = resp.json()
    except Exception as exc:
        log.warning("County officials related records query failed: %s", exc)
        return county, district, []

    officials = []
    for group in data2.get("relatedRecordGroups", []):
        for rec in group.get("relatedRecords", []):
            a = rec.get("attributes", {})
            officials.append({
                "office": (a.get("Office") or "").strip(),
                "name":   (a.get("Name")   or "").strip(),
                "title":  (a.get("Title")  or "").strip(),
            })

    return county, district, officials


def parse_county_officials(officials: list) -> dict:
    """
    Map raw official records to fixed output columns.

    Office matching order matters — check specific strings before broad ones:
      "county executive"            → county_executive        (New Castle only)
      "council president" / title   → county_council_president (NCC & Kent president)
      "clerk of the peace"          → clerk_of_peace
      "register of wills"           → register_of_wills
      "recorder of deeds"           → recorder_of_deeds
      "sheriff"                     → county_sheriff
      "council" / "levy court"      → county_council_member   (district rep)

    Kent's Levy Court president is identified by Title == "President", not by
    the Office string, so we check Title after the broad council/levy court match.
    """
    result = {
        "county_executive": "",
        "county_council_president": "",
        "county_council_member": "",
        "county_sheriff": "",
        "clerk_of_peace": "",
        "register_of_wills": "",
        "recorder_of_deeds": "",
    }
    council_members = []

    for official in officials:
        office = official["office"].lower()
        name   = official["name"]
        title  = official["title"].lower()
        if not name:
            continue

        if "county executive" in office:
            result["county_executive"] = name
        elif "council president" in office or "president of county council" in office:
            result["county_council_president"] = name
        elif "clerk of the peace" in office or "clerk of peace" in office:
            result["clerk_of_peace"] = name
        elif "register of wills" in office:
            result["register_of_wills"] = name
        elif "recorder of deeds" in office:
            result["recorder_of_deeds"] = name
        elif "sheriff" in office:
            result["county_sheriff"] = name
        elif "council" in office or "levy court" in office:
            # Levy Court / Council president is identified by the Title field
            if title == "president":
                result["county_council_president"] = name
            else:
                council_members.append(name)

    result["county_council_member"] = "; ".join(council_members)
    return result


def query_wilmington_city_council(session: requests.Session, x: float, y: float) -> dict:
    """
    Query Layer 5 (Wilmington City Council Districts).
    Returns empty strings for addresses outside Wilmington.
    """
    fields = ["NAME", "PRESIDENT", "COUNCIL_ME", "ATLARGE", "ATLARGE1", "ATLARGE2", "ATLARGE3"]
    attrs = query_political_layer(session, 5, x, y, fields)

    empty = {
        "wilm_city_council_district": "",
        "wilm_council_president": "",
        "wilm_council_member": "",
        "wilm_council_at_large": "",
    }
    if not attrs:
        return empty

    at_large = [
        attrs.get("ATLARGE")  or "",
        attrs.get("ATLARGE1") or "",
        attrs.get("ATLARGE2") or "",
        attrs.get("ATLARGE3") or "",
    ]

    return {
        "wilm_city_council_district": str(attrs.get("NAME")      or ""),
        "wilm_council_president":     str(attrs.get("PRESIDENT") or ""),
        "wilm_council_member":        str(attrs.get("COUNCIL_ME") or ""),
        "wilm_council_at_large":      "; ".join(m for m in at_large if m),
    }


def query_school_board(session: requests.Session, x: float, y: float) -> dict:
    """
    Query Layer 4 (School Board Districts).
    Board member names are stored directly in layer attributes — no secondary lookup needed.
    """
    fields = [
        "NAME", "NOM_DIST",
        "DISTRICT_BOARD_MEMBER_1", "DISTRICT_BOARD_MEMBER_2",
        "AT_LARGE_BOARD_MEMBER_1", "AT_LARGE_BOARD_MEMBER_2",
        "AT_LARGE_BOARD_MEMBER_3", "AT_LARGE_BOARD_MEMBER_4",
        "AT_LARGE_BOARD_MEMBER_5",
    ]
    attrs = query_political_layer(session, 4, x, y, fields)

    empty = {
        "school_district": "",
        "school_board_district": "",
        "school_board_members_district": "",
        "school_board_members_at_large": "",
    }
    if not attrs:
        return empty

    district_members = [
        attrs.get("DISTRICT_BOARD_MEMBER_1") or "",
        attrs.get("DISTRICT_BOARD_MEMBER_2") or "",
    ]
    at_large_members = [
        attrs.get("AT_LARGE_BOARD_MEMBER_1") or "",
        attrs.get("AT_LARGE_BOARD_MEMBER_2") or "",
        attrs.get("AT_LARGE_BOARD_MEMBER_3") or "",
        attrs.get("AT_LARGE_BOARD_MEMBER_4") or "",
        attrs.get("AT_LARGE_BOARD_MEMBER_5") or "",
    ]

    return {
        "school_district":               str(attrs.get("NAME")     or ""),
        "school_board_district":         str(attrs.get("NOM_DIST") or ""),
        "school_board_members_district": "; ".join(m for m in district_members if m),
        "school_board_members_at_large": "; ".join(m for m in at_large_members if m),
    }


# ---------------------------------------------------------------------------
# Full address lookup
# ---------------------------------------------------------------------------

def lookup_address(session: requests.Session, address: str) -> dict:
    result = {col: "" for col in OUTPUT_COLS}

    candidate = geocode_address(session, address)
    if not candidate:
        result["geocoded_address"] = "NOT FOUND"
        return result

    loc = candidate["location"]
    x, y = loc["x"], loc["y"]
    result["geocoded_address"] = candidate.get("address", address)
    result["geocode_score"]    = str(candidate.get("score", ""))

    # State Senate (Layer 1)
    attrs = query_political_layer(session, 1, x, y, ["DISTRICT", "NAME", "URL"])
    if attrs:
        result["senate_district"] = str(attrs.get("DISTRICT") or "")
        result["senator"]         = str(attrs.get("NAME")     or "")
        result["senator_url"]     = str(attrs.get("URL")      or "")

    # State House (Layer 2)
    attrs = query_political_layer(session, 2, x, y, ["DISTRICT", "NAME", "URL"])
    if attrs:
        result["house_district"]      = str(attrs.get("DISTRICT") or "")
        result["representative"]      = str(attrs.get("NAME")     or "")
        result["representative_url"]  = str(attrs.get("URL")      or "")

    # County officials (two-step)
    county, county_district, officials = query_county_officials(session, x, y)
    result["county"]          = county or ""
    result["county_district"] = county_district or ""
    if officials:
        result.update(parse_county_officials(officials))

    # Wilmington City Council (Layer 5 — empty outside Wilmington)
    result.update(query_wilmington_city_council(session, x, y))

    # School board (Layer 4)
    result.update(query_school_board(session, x, y))

    return result


# ---------------------------------------------------------------------------
# CSV processing
# ---------------------------------------------------------------------------

def detect_address_column(fieldnames: list) -> Optional[str]:
    for name in fieldnames:
        if name.lower().strip() in (
            "address", "addr", "street", "street_address",
            "full_address", "mailing_address", "property_address",
        ):
            return name
    return None


def process_csv(
    input_path: str,
    output_path: str,
    address_col: Optional[str],
    delay: float,
) -> None:
    with open(input_path, newline="", encoding="utf-8-sig") as f_in:
        reader = csv.DictReader(f_in)
        if not reader.fieldnames:
            log.error("Input CSV has no header row.")
            sys.exit(1)

        col = address_col or detect_address_column(reader.fieldnames)
        if not col:
            log.error(
                "Could not auto-detect address column. "
                "Use --address-col to specify. Available: %s",
                ", ".join(reader.fieldnames),
            )
            sys.exit(1)
        if col not in reader.fieldnames:
            log.error(
                "Column '%s' not found. Available: %s",
                col,
                ", ".join(reader.fieldnames),
            )
            sys.exit(1)

        log.info("Using address column: '%s'", col)
        out_fields = list(reader.fieldnames) + OUTPUT_COLS

        session = requests.Session()
        session.headers["User-Agent"] = "de-election-lookup/1.0"

        with open(output_path, "w", newline="", encoding="utf-8") as f_out:
            writer = csv.DictWriter(f_out, fieldnames=out_fields, extrasaction="ignore")
            writer.writeheader()

            rows = list(reader)
            total = len(rows)
            for i, row in enumerate(rows, 1):
                address = row.get(col, "").strip()
                log.info("[%d/%d] %s", i, total, address)

                if not address:
                    lookup = {c: "" for c in OUTPUT_COLS}
                    lookup["geocoded_address"] = "SKIPPED (empty)"
                else:
                    lookup = lookup_address(session, address)

                writer.writerow({**row, **lookup})

                if delay > 0 and i < total:
                    time.sleep(delay)

    log.info("Done. Output written to: %s", output_path)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Comprehensive Delaware election lookup: state legislators, "
            "county officials, Wilmington City Council, and school board district."
        )
    )
    parser.add_argument("input", help="Path to input CSV file")
    parser.add_argument(
        "--address-col", "-a",
        metavar="COLUMN",
        help="Name of the address column (auto-detected if omitted)",
    )
    parser.add_argument(
        "--output", "-o",
        metavar="FILE",
        default="output.csv",
        help="Output CSV path (default: output.csv)",
    )
    parser.add_argument(
        "--delay", "-d",
        type=float,
        default=0.25,
        metavar="SECONDS",
        help="Pause between lookups in seconds (default: 0.25)",
    )
    args = parser.parse_args()

    process_csv(args.input, args.output, args.address_col, args.delay)


if __name__ == "__main__":
    main()
