# de_elections_address_lookup.ps1
# Generated by AI (Claude).
#
# MIT License — Copyright (c) 2026 Pat Hennessy
# See LICENSE file for full text.
#
# Reads a CSV with an address column, geocodes each address via the Delaware
# FirstMap locator, then performs point-in-polygon queries to retrieve:
#
#   - State Senate district & senator
#   - State House district & representative
#   - County officials (executive, council/levy court, sheriff, clerk of peace,
#     register of wills, recorder of deeds)
#   - Wilmington City Council district & members (Wilmington addresses only)
#   - School board district & board members
#
# County administrative structures vary:
#   - New Castle: County Executive + County Council (with President)
#   - Kent:       Levy Court Commissioners (president identified by Title field)
#   - Sussex:     County Council (no County Executive)
#
# Usage:
#   .\de_elections_address_lookup.ps1 -InputFile input.csv -OutputFile results.csv
#   .\de_elections_address_lookup.ps1 -InputFile input.csv -AddressCol "Property Address" -OutputFile results.csv

[CmdletBinding()]
param (
    [Parameter(Mandatory = $true, Position = 0)]
    [string]$InputFile,

    [Parameter(Mandatory = $false)]
    [string]$AddressCol = "",

    [Parameter(Mandatory = $false)]
    [string]$OutputFile = "output.csv",

    [Parameter(Mandatory = $false)]
    [double]$Delay = 0.25
)

# ---------------------------------------------------------------------------
# API endpoints
# ---------------------------------------------------------------------------

$GEOCODE_URL          = "https://enterprise.firstmap.delaware.gov/arcgis/rest/services/Location/Delaware_FirstMap_Locator/GeocodeServer/findAddressCandidates"
$FEATURE_SERVER_BASE  = "https://enterprise.firstmap.delaware.gov/arcgis/rest/services/Boundaries/DE_Political_Boundaries/FeatureServer"
$COUNTY_OFFICIALS_URL = "https://services1.arcgis.com/bFDgLqS5IyUBQLAd/arcgis/rest/services/County_Officials_gdb/FeatureServer/0"

$AUTO_DETECT_NAMES = @("address", "addr", "street", "street_address", "full_address", "mailing_address", "property_address")

$OUTPUT_COLS = @(
    "geocoded_address",
    "geocode_score",
    "senate_district",
    "senator",
    "senator_url",
    "house_district",
    "representative",
    "representative_url",
    "county",
    "county_district",
    "county_executive",
    "county_council_president",
    "county_council_member",
    "county_sheriff",
    "clerk_of_peace",
    "register_of_wills",
    "recorder_of_deeds",
    "wilm_city_council_district",
    "wilm_council_president",
    "wilm_council_member",
    "wilm_council_at_large",
    "school_district",
    "school_board_district",
    "school_board_members_district",
    "school_board_members_at_large"
)

# ---------------------------------------------------------------------------
# Proxy detection
# ---------------------------------------------------------------------------

$script:ProxyParams = @{}
$detectedProxy = $env:HTTPS_PROXY
if (-not $detectedProxy) { $detectedProxy = $env:HTTP_PROXY }
if ($detectedProxy) {
    Write-Host "INFO  Using proxy: $detectedProxy" -ForegroundColor Cyan
    $script:ProxyParams["Proxy"] = $detectedProxy
    $script:ProxyParams["ProxyUseDefaultCredentials"] = $true
}

# ---------------------------------------------------------------------------
# API helpers
# ---------------------------------------------------------------------------

function Invoke-Geocode($address) {
    $params = @{
        SingleLine   = $address
        maxLocations = 1
        outSR        = '{"wkid":102100}'
        f            = "json"
    }
    try {
        $resp = Invoke-RestMethod -Uri $GEOCODE_URL -Method Get -Body $params -TimeoutSec 15 -UserAgent "de-election-lookup/1.0" @script:ProxyParams
        $candidates = $resp.candidates
        if (-not $candidates -or $candidates.Count -eq 0) {
            Write-Warning "No geocode match for: $address"
            return $null
        }
        return $candidates[0]
    } catch {
        Write-Warning "Geocode failed for '$address': $_"
        return $null
    }
}

function Invoke-PoliticalLayerQuery($layerId, $x, $y, $fields) {
    $geometry = "{`"x`":$x,`"y`":$y}"
    $params = @{
        f                 = "json"
        geometry          = $geometry
        geometryType      = "esriGeometryPoint"
        inSR              = "102100"
        spatialRel        = "esriSpatialRelIntersects"
        outFields         = ($fields -join ",")
        returnGeometry    = "false"
        resultRecordCount = 500
        where             = "1=1"
    }
    $url = "$FEATURE_SERVER_BASE/$layerId/query"
    try {
        $resp     = Invoke-RestMethod -Uri $url -Method Get -Body $params -TimeoutSec 15 -UserAgent "de-election-lookup/1.0" @script:ProxyParams
        $features = $resp.features
        if (-not $features -or $features.Count -eq 0) { return $null }
        if ($resp.exceededTransferLimit -and $features.Count -eq 0) {
            Write-Warning "Layer ${layerId}: exceededTransferLimit with 0 features"
            return $null
        }
        return $features[0].attributes
    } catch {
        Write-Warning "Layer $layerId query failed: $_"
        return $null
    }
}

function Invoke-CountyOfficialsLookup($x, $y) {
    # Step 1 — spatial query
    $geometry = "{`"x`":$x,`"y`":$y}"
    $params1 = @{
        f                 = "json"
        geometry          = $geometry
        geometryType      = "esriGeometryPoint"
        inSR              = "102100"
        spatialRel        = "esriSpatialRelIntersects"
        outFields         = "OBJECTID,COUNTY,DISTRICT"
        returnGeometry    = "false"
        resultRecordCount = 500
    }
    try {
        $resp1    = Invoke-RestMethod -Uri "$COUNTY_OFFICIALS_URL/query" -Method Get -Body $params1 -TimeoutSec 15 -UserAgent "de-election-lookup/1.0" @script:ProxyParams
        $features = $resp1.features
        if (-not $features -or $features.Count -eq 0) {
            Write-Warning "No county officials district found for ($x, $y)"
            return $null, $null, @()
        }
    } catch {
        Write-Warning "County officials spatial query failed: $_"
        return $null, $null, @()
    }

    $attrs1   = $features[0].attributes
    $oid      = $attrs1.OBJECTID
    $county   = if ($attrs1.COUNTY)   { [string]$attrs1.COUNTY   } else { "" }
    $district = if ($attrs1.DISTRICT) { [string]$attrs1.DISTRICT } else { "" }

    if ($null -eq $oid) { return $county, $district, @() }

    # Step 2 — related records
    $params2 = @{
        f              = "json"
        objectIds      = [string]$oid
        outFields      = "County,Office,Name,Title"
        relationshipId = 0
        returnGeometry = "false"
    }
    try {
        $resp2  = Invoke-RestMethod -Uri "$COUNTY_OFFICIALS_URL/queryRelatedRecords" -Method Get -Body $params2 -TimeoutSec 15 -UserAgent "de-election-lookup/1.0" @script:ProxyParams
        $groups = $resp2.relatedRecordGroups
    } catch {
        Write-Warning "County officials related records query failed: $_"
        return $county, $district, @()
    }

    $officials = [System.Collections.Generic.List[hashtable]]::new()
    foreach ($group in $groups) {
        foreach ($rec in $group.relatedRecords) {
            $a = $rec.attributes
            $officials.Add(@{
                office = if ($a.Office) { $a.Office.Trim() } else { "" }
                name   = if ($a.Name)   { $a.Name.Trim()   } else { "" }
                title  = if ($a.Title)  { $a.Title.Trim()  } else { "" }
            })
        }
    }

    return $county, $district, $officials
}

function ConvertTo-CountyOfficialFields($officials) {
    $result = [ordered]@{
        county_executive         = ""
        county_council_president = ""
        county_council_member    = ""
        county_sheriff           = ""
        clerk_of_peace           = ""
        register_of_wills        = ""
        recorder_of_deeds        = ""
    }
    $councilMembers = [System.Collections.Generic.List[string]]::new()

    foreach ($official in $officials) {
        $office = $official.office.ToLower()
        $name   = $official.name
        $title  = $official.title.ToLower()
        if (-not $name) { continue }

        if ($office -like "*county executive*") {
            $result["county_executive"] = $name
        } elseif ($office -like "*council president*" -or $office -like "*president of county council*") {
            $result["county_council_president"] = $name
        } elseif ($office -like "*clerk of the peace*" -or $office -like "*clerk of peace*") {
            $result["clerk_of_peace"] = $name
        } elseif ($office -like "*register of wills*") {
            $result["register_of_wills"] = $name
        } elseif ($office -like "*recorder of deeds*") {
            $result["recorder_of_deeds"] = $name
        } elseif ($office -like "*sheriff*") {
            $result["county_sheriff"] = $name
        } elseif ($office -like "*council*" -or $office -like "*levy court*") {
            # Levy Court / Council president is identified by the Title field
            if ($title -eq "president") {
                $result["county_council_president"] = $name
            } else {
                $councilMembers.Add($name)
            }
        }
    }

    $result["county_council_member"] = ($councilMembers -join "; ")
    return $result
}

function Invoke-WilmingtonCityCouncilQuery($x, $y) {
    $fields = @("NAME", "PRESIDENT", "COUNCIL_ME", "ATLARGE", "ATLARGE1", "ATLARGE2", "ATLARGE3")
    $attrs  = Invoke-PoliticalLayerQuery 5 $x $y $fields

    $empty = [ordered]@{
        wilm_city_council_district = ""
        wilm_council_president     = ""
        wilm_council_member        = ""
        wilm_council_at_large      = ""
    }
    if (-not $attrs) { return $empty }

    $atLargeMembers = @(
        $attrs.ATLARGE,
        $attrs.ATLARGE1,
        $attrs.ATLARGE2,
        $attrs.ATLARGE3
    ) | Where-Object { $_ }

    return [ordered]@{
        wilm_city_council_district = if ($attrs.NAME)       { [string]$attrs.NAME       } else { "" }
        wilm_council_president     = if ($attrs.PRESIDENT)  { [string]$attrs.PRESIDENT  } else { "" }
        wilm_council_member        = if ($attrs.COUNCIL_ME) { [string]$attrs.COUNCIL_ME } else { "" }
        wilm_council_at_large      = ($atLargeMembers -join "; ")
    }
}

function Invoke-SchoolBoardQuery($x, $y) {
    $fields = @(
        "NAME", "NOM_DIST",
        "DISTRICT_BOARD_MEMBER_1", "DISTRICT_BOARD_MEMBER_2",
        "AT_LARGE_BOARD_MEMBER_1", "AT_LARGE_BOARD_MEMBER_2",
        "AT_LARGE_BOARD_MEMBER_3", "AT_LARGE_BOARD_MEMBER_4",
        "AT_LARGE_BOARD_MEMBER_5"
    )
    $attrs = Invoke-PoliticalLayerQuery 4 $x $y $fields

    $empty = [ordered]@{
        school_district               = ""
        school_board_district         = ""
        school_board_members_district = ""
        school_board_members_at_large = ""
    }
    if (-not $attrs) { return $empty }

    $districtMembers = @(
        $attrs.DISTRICT_BOARD_MEMBER_1,
        $attrs.DISTRICT_BOARD_MEMBER_2
    ) | Where-Object { $_ }

    $atLargeMembers = @(
        $attrs.AT_LARGE_BOARD_MEMBER_1,
        $attrs.AT_LARGE_BOARD_MEMBER_2,
        $attrs.AT_LARGE_BOARD_MEMBER_3,
        $attrs.AT_LARGE_BOARD_MEMBER_4,
        $attrs.AT_LARGE_BOARD_MEMBER_5
    ) | Where-Object { $_ }

    return [ordered]@{
        school_district               = if ($attrs.NAME)     { [string]$attrs.NAME     } else { "" }
        school_board_district         = if ($attrs.NOM_DIST) { [string]$attrs.NOM_DIST } else { "" }
        school_board_members_district = ($districtMembers -join "; ")
        school_board_members_at_large = ($atLargeMembers -join "; ")
    }
}

function Invoke-AddressLookup($address) {
    $result = [ordered]@{}
    foreach ($col in $OUTPUT_COLS) { $result[$col] = "" }

    $candidate = Invoke-Geocode $address
    if (-not $candidate) {
        $result["geocoded_address"] = "NOT FOUND"
        return $result
    }

    $x = $candidate.location.x
    $y = $candidate.location.y
    $result["geocoded_address"] = $candidate.address
    $result["geocode_score"]    = [string]$candidate.score

    # State Senate (Layer 1)
    $attrs = Invoke-PoliticalLayerQuery 1 $x $y @("DISTRICT", "NAME", "URL")
    if ($attrs) {
        $result["senate_district"] = if ($attrs.DISTRICT) { [string]$attrs.DISTRICT } else { "" }
        $result["senator"]         = if ($attrs.NAME)     { [string]$attrs.NAME     } else { "" }
        $result["senator_url"]     = if ($attrs.URL)      { [string]$attrs.URL      } else { "" }
    }

    # State House (Layer 2)
    $attrs = Invoke-PoliticalLayerQuery 2 $x $y @("DISTRICT", "NAME", "URL")
    if ($attrs) {
        $result["house_district"]     = if ($attrs.DISTRICT) { [string]$attrs.DISTRICT } else { "" }
        $result["representative"]     = if ($attrs.NAME)     { [string]$attrs.NAME     } else { "" }
        $result["representative_url"] = if ($attrs.URL)      { [string]$attrs.URL      } else { "" }
    }

    # County officials
    $county, $countyDistrict, $officials = Invoke-CountyOfficialsLookup $x $y
    $result["county"]          = if ($county)         { $county         } else { "" }
    $result["county_district"] = if ($countyDistrict) { $countyDistrict } else { "" }
    if ($officials -and $officials.Count -gt 0) {
        $parsed = ConvertTo-CountyOfficialFields $officials
        foreach ($key in $parsed.Keys) { $result[$key] = $parsed[$key] }
    }

    # Wilmington City Council (Layer 5 — empty outside Wilmington)
    $wilm = Invoke-WilmingtonCityCouncilQuery $x $y
    foreach ($key in $wilm.Keys) { $result[$key] = $wilm[$key] }

    # School board (Layer 4)
    $school = Invoke-SchoolBoardQuery $x $y
    foreach ($key in $school.Keys) { $result[$key] = $school[$key] }

    return $result
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

if (-not (Test-Path $InputFile)) {
    Write-Error "Input file not found: $InputFile"
    exit 1
}

$rows = Import-Csv -Path $InputFile -Encoding UTF8
if ($rows.Count -eq 0) {
    Write-Error "Input CSV is empty or has no data rows."
    exit 1
}

$inputFields = $rows[0].PSObject.Properties.Name

# Resolve address column
$col = $AddressCol
if (-not $col) {
    foreach ($name in $inputFields) {
        if ($AUTO_DETECT_NAMES -contains $name.ToLower().Trim()) {
            $col = $name
            break
        }
    }
}
if (-not $col) {
    Write-Error "Could not auto-detect address column. Use -AddressCol. Available: $($inputFields -join ', ')"
    exit 1
}
if ($inputFields -notcontains $col) {
    Write-Error "Column '$col' not found. Available: $($inputFields -join ', ')"
    exit 1
}

Write-Host "INFO  Using address column: '$col'" -ForegroundColor Cyan

$allFields = $inputFields + $OUTPUT_COLS
$results   = [System.Collections.Generic.List[object]]::new()
$total     = $rows.Count

for ($i = 0; $i -lt $total; $i++) {
    $row     = $rows[$i]
    $address = $row.$col.Trim()
    Write-Host "INFO  [$($i+1)/$total] $address" -ForegroundColor Cyan

    if (-not $address) {
        $lookup = [ordered]@{}
        foreach ($col2 in $OUTPUT_COLS) { $lookup[$col2] = "" }
        $lookup["geocoded_address"] = "SKIPPED (empty)"
    } else {
        $lookup = Invoke-AddressLookup $address
    }

    $outRow = [ordered]@{}
    foreach ($field in $inputFields) { $outRow[$field] = $row.$field }
    foreach ($key in $lookup.Keys)   { $outRow[$key]   = $lookup[$key] }

    $results.Add([PSCustomObject]$outRow)

    if ($Delay -gt 0 -and $i -lt ($total - 1)) {
        Start-Sleep -Milliseconds ([int]($Delay * 1000))
    }
}

$results | Select-Object $allFields | Export-Csv -Path $OutputFile -NoTypeInformation -Encoding UTF8
Write-Host "INFO  Done. Output written to: $OutputFile" -ForegroundColor Green
