"""
de_legislator_lookup.py
-----------------------
Generated by AI (Claude).

MIT License — Copyright (c) 2026 Pat Hennessy
See LICENSE file for full text.

Reads a CSV with an address column, geocodes each address via the Delaware
FirstMap locator, then performs point-in-polygon queries against the
DE Political Boundaries FeatureServer to retrieve:

  - State Senate district & senator
  - State House district & representative

Usage:
    python de_legislator_lookup.py input.csv --address-col "Address" --output output.csv

Requirements:
    pip install requests
"""

import argparse
import csv
import json
import logging
import sys
import time
from typing import Optional

import requests

# ---------------------------------------------------------------------------
# API endpoints
# ---------------------------------------------------------------------------

GEOCODE_URL = (
    "https://enterprise.firstmap.delaware.gov/arcgis/rest/services/"
    "Location/Delaware_FirstMap_Locator/GeocodeServer/findAddressCandidates"
)

FEATURE_SERVER_BASE = (
    "https://enterprise.firstmap.delaware.gov/arcgis/rest/services/"
    "Boundaries/DE_Political_Boundaries/FeatureServer"
)

# Layer IDs and the fields we want from each
LAYERS = {
    "senate": {
        "id": 1,
        "fields": ["DISTRICT", "NAME", "URL"],
    },
    "house": {
        "id": 2,
        "fields": ["DISTRICT", "NAME", "URL"],
    },
}

# Output column mapping: (layer_key, source_field, output_col_name)
# For _geo entries the second element is already the output column name.
OUTPUT_COLUMNS = [
    # Geocode info
    ("_geo", "geocoded_address"),
    ("_geo", "geocode_score"),
    # Senate
    ("senate", "DISTRICT", "senate_district"),
    ("senate", "NAME",     "senator"),
    ("senate", "URL",      "senator_url"),
    # House
    ("house", "DISTRICT", "house_district"),
    ("house", "NAME",     "representative"),
    ("house", "URL",      "representative_url"),
]

logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s  %(message)s",
    stream=sys.stderr,
)
log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# API helpers
# ---------------------------------------------------------------------------

def geocode_address(session: requests.Session, address: str) -> Optional[dict]:
    """
    Geocode a single-line address using the Delaware FirstMap locator.
    Returns the top candidate dict or None if no match found.
    """
    params = {
        "SingleLine": address,
        "maxLocations": 1,
        "outSR": json.dumps({"wkid": 102100}),  # Web Mercator, matches FeatureServer
        "f": "json",
    }
    try:
        resp = session.get(GEOCODE_URL, params=params, timeout=15)
        resp.raise_for_status()
        data = resp.json()
    except Exception as exc:
        log.warning("Geocode request failed for '%s': %s", address, exc)
        return None

    candidates = data.get("candidates", [])
    if not candidates:
        log.warning("No geocode match for: %s", address)
        return None

    return candidates[0]  # keys: address, location {x, y}, score


def query_layer(
    session: requests.Session,
    layer_id: int,
    x: float,
    y: float,
    fields: list,
) -> Optional[dict]:
    """
    Point-in-polygon query against a FeatureServer layer.
    Returns the attributes dict of the first matching feature, or None.
    """
    params = {
        "f": "json",
        "geometry": json.dumps({"x": x, "y": y}),
        "geometryType": "esriGeometryPoint",
        "inSR": "102100",
        "spatialRel": "esriSpatialRelIntersects",
        "outFields": ",".join(fields),
        "returnGeometry": "false",
        "resultRecordCount": 500,
    }
    url = f"{FEATURE_SERVER_BASE}/{layer_id}/query"
    try:
        resp = session.get(url, params=params, timeout=15)
        resp.raise_for_status()
        data = resp.json()
    except Exception as exc:
        log.warning("Layer %d query failed: %s", layer_id, exc)
        return None

    features = data.get("features", [])
    if not features:
        return None
    return features[0].get("attributes", {})


def lookup_address(session: requests.Session, address: str) -> dict:
    """
    Full lookup: geocode + senate and house layer queries.
    Returns a flat dict of all output fields.
    """
    # Build result with empty defaults for every output column
    result = {}
    for entry in OUTPUT_COLUMNS:
        col_name = entry[2] if len(entry) == 3 else entry[1]
        result[col_name] = ""

    # Geocode
    candidate = geocode_address(session, address)
    if not candidate:
        result["geocoded_address"] = "NOT FOUND"
        return result

    loc = candidate["location"]
    x, y = loc["x"], loc["y"]
    result["geocoded_address"] = candidate.get("address", address)
    result["geocode_score"] = str(candidate.get("score", ""))

    # Query each FeatureServer layer
    for layer_key, layer_cfg in LAYERS.items():
        attrs = query_layer(session, layer_cfg["id"], x, y, layer_cfg["fields"])
        if not attrs:
            continue
        for entry in OUTPUT_COLUMNS:
            if entry[0] != layer_key:
                continue
            field = entry[1]
            col_name = entry[2] if len(entry) == 3 else entry[1]
            val = attrs.get(field)
            result[col_name] = "" if val is None else str(val)

    return result


# ---------------------------------------------------------------------------
# CSV processing
# ---------------------------------------------------------------------------

def detect_address_column(fieldnames: list) -> Optional[str]:
    """Heuristic: find a column whose name suggests it holds addresses."""
    for name in fieldnames:
        low = name.lower().strip()
        if low in ("address", "addr", "street", "street_address",
                   "full_address", "mailing_address", "property_address"):
            return name
    return None


def build_output_fieldnames(input_fields: list) -> list:
    output_cols = [
        entry[2] if len(entry) == 3 else entry[1]
        for entry in OUTPUT_COLUMNS
    ]
    return input_fields + output_cols


def process_csv(
    input_path: str,
    output_path: str,
    address_col: Optional[str],
    delay: float,
) -> None:
    with open(input_path, newline="", encoding="utf-8-sig") as f_in:
        reader = csv.DictReader(f_in)
        if not reader.fieldnames:
            log.error("Input CSV has no header row.")
            sys.exit(1)

        # Resolve address column
        col = address_col or detect_address_column(reader.fieldnames)
        if not col:
            log.error(
                "Could not auto-detect address column. "
                "Use --address-col to specify. Available columns: %s",
                ", ".join(reader.fieldnames),
            )
            sys.exit(1)
        if col not in reader.fieldnames:
            log.error(
                "Column '%s' not found. Available: %s",
                col,
                ", ".join(reader.fieldnames),
            )
            sys.exit(1)

        log.info("Using address column: '%s'", col)
        out_fields = build_output_fieldnames(list(reader.fieldnames))

        with open(output_path, "w", newline="", encoding="utf-8") as f_out:
            writer = csv.DictWriter(f_out, fieldnames=out_fields, extrasaction="ignore")
            writer.writeheader()

            rows = list(reader)
            total = len(rows)
            for i, row in enumerate(rows, 1):
                address = row.get(col, "").strip()
                log.info("[%d/%d] Looking up: %s", i, total, address)

                if not address:
                    lookup = {
                        entry[2] if len(entry) == 3 else entry[1]: ""
                        for entry in OUTPUT_COLUMNS
                    }
                    lookup["geocoded_address"] = "SKIPPED (empty)"
                else:
                    session = requests.Session()
                    session.headers["User-Agent"] = "de-legislator-lookup/1.0"
                    lookup = lookup_address(session, address)

                writer.writerow({**row, **lookup})

                if delay > 0 and i < total:
                    time.sleep(delay)

    log.info("Done. Output written to: %s", output_path)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Look up Delaware legislative district info for addresses in a CSV."
    )
    parser.add_argument("input", help="Path to input CSV file")
    parser.add_argument(
        "--address-col", "-a",
        metavar="COLUMN",
        help="Name of the column containing addresses (auto-detected if omitted)",
    )
    parser.add_argument(
        "--output", "-o",
        metavar="FILE",
        default="output.csv",
        help="Path for the output CSV (default: output.csv)",
    )
    parser.add_argument(
        "--delay", "-d",
        type=float,
        default=0.25,
        metavar="SECONDS",
        help="Pause between address lookups to be polite to the API (default: 0.25s)",
    )
    args = parser.parse_args()

    process_csv(
        input_path=args.input,
        output_path=args.output,
        address_col=args.address_col,
        delay=args.delay,
    )


if __name__ == "__main__":
    main()
