# de_legislator_lookup.ps1
# Generated by AI (Claude).
#
# MIT License — Copyright (c) 2026 Pat Hennessy
# See LICENSE file for full text.
#
# Reads a CSV with an address column, geocodes each address via the Delaware
# FirstMap locator, then performs point-in-polygon queries against the
# DE Political Boundaries FeatureServer to retrieve:
#
#   - State Senate district & senator
#   - State House district & representative
#
# Usage:
#   .\de_legislator_lookup.ps1 -InputFile input.csv -OutputFile results.csv
#   .\de_legislator_lookup.ps1 -InputFile input.csv -AddressCol "Property Address" -OutputFile results.csv

[CmdletBinding()]
param (
    [Parameter(Mandatory = $true, Position = 0)]
    [string]$InputFile,

    [Parameter(Mandatory = $false)]
    [string]$AddressCol = "",

    [Parameter(Mandatory = $false)]
    [string]$OutputFile = "output.csv",

    [Parameter(Mandatory = $false)]
    [double]$Delay = 0.25
)

# ---------------------------------------------------------------------------
# API endpoints
# ---------------------------------------------------------------------------

$GEOCODE_URL = "https://enterprise.firstmap.delaware.gov/arcgis/rest/services/Location/Delaware_FirstMap_Locator/GeocodeServer/findAddressCandidates"
$FEATURE_SERVER_BASE = "https://enterprise.firstmap.delaware.gov/arcgis/rest/services/Boundaries/DE_Political_Boundaries/FeatureServer"

# Layer IDs and fields to request
$LAYERS = [ordered]@{
    senate = @{ id = 1; fields = @("DISTRICT", "NAME", "URL") }
    house  = @{ id = 2; fields = @("DISTRICT", "NAME", "URL") }
}

# Output columns: [layer_key, source_field, output_col_name]
# _geo entries use [layer_key, output_col_name] (no source field)
$OUTPUT_COLUMNS = @(
    @("_geo", "geocoded_address"),
    @("_geo", "geocode_score"),
    @("senate", "DISTRICT", "senate_district"),
    @("senate", "NAME",     "senator"),
    @("senate", "URL",      "senator_url"),
    @("house",  "DISTRICT", "house_district"),
    @("house",  "NAME",     "representative"),
    @("house",  "URL",      "representative_url")
)

# Auto-detected address column names
$AUTO_DETECT_NAMES = @("address", "addr", "street", "street_address", "full_address", "mailing_address", "property_address")

# ---------------------------------------------------------------------------
# Proxy detection
#
# Invoke-RestMethod uses the system proxy on Windows automatically, but does
# NOT read HTTP_PROXY / HTTPS_PROXY env vars on any platform. We detect those
# here and pass them explicitly so the script works in both cases.
# ---------------------------------------------------------------------------

$script:ProxyParams = @{}
$detectedProxy = $env:HTTPS_PROXY
if (-not $detectedProxy) { $detectedProxy = $env:HTTP_PROXY }
if ($detectedProxy) {
    Write-Host "INFO  Using proxy from environment: $detectedProxy" -ForegroundColor Cyan
    $script:ProxyParams["Proxy"] = $detectedProxy
    # Pass Windows credentials through if the proxy requires them
    $script:ProxyParams["ProxyUseDefaultCredentials"] = $true
}

# ---------------------------------------------------------------------------
# Functions
# ---------------------------------------------------------------------------

function Get-OutputColName($entry) {
    if ($entry.Count -eq 3) { return $entry[2] } else { return $entry[1] }
}

function Invoke-Geocode($address) {
    $params = @{
        SingleLine   = $address
        maxLocations = 1
        outSR        = '{"wkid":102100}'
        f            = "json"
    }
    try {
        $resp = Invoke-RestMethod -Uri $GEOCODE_URL -Method Get -Body $params -TimeoutSec 15 -UserAgent "de-legislator-lookup/1.0" @script:ProxyParams
        $candidates = $resp.candidates
        if (-not $candidates -or $candidates.Count -eq 0) {
            Write-Warning "No geocode match for: $address"
            return $null
        }
        return $candidates[0]
    } catch {
        Write-Warning "Geocode request failed for '$address': $_"
        return $null
    }
}

function Invoke-LayerQuery($layerId, $x, $y, $fields) {
    $geometry = "{`"x`":$x,`"y`":$y}"
    $params = @{
        f                 = "json"
        geometry          = $geometry
        geometryType      = "esriGeometryPoint"
        inSR              = "102100"
        spatialRel        = "esriSpatialRelIntersects"
        outFields         = ($fields -join ",")
        returnGeometry    = "false"
        resultRecordCount = 500
    }
    $url = "$FEATURE_SERVER_BASE/$layerId/query"
    try {
        $resp     = Invoke-RestMethod -Uri $url -Method Get -Body $params -TimeoutSec 15 -UserAgent "de-legislator-lookup/1.0" @script:ProxyParams
        $features = $resp.features
        if (-not $features -or $features.Count -eq 0) { return $null }
        return $features[0].attributes
    } catch {
        Write-Warning "Layer $layerId query failed: $_"
        return $null
    }
}

function Invoke-AddressLookup($address) {
    # Build result with empty defaults
    $result = [ordered]@{}
    foreach ($entry in $OUTPUT_COLUMNS) {
        $result[(Get-OutputColName $entry)] = ""
    }

    $candidate = Invoke-Geocode $address
    if (-not $candidate) {
        $result["geocoded_address"] = "NOT FOUND"
        return $result
    }

    $x = $candidate.location.x
    $y = $candidate.location.y
    $result["geocoded_address"] = $candidate.address
    $result["geocode_score"]    = [string]$candidate.score

    foreach ($layerKey in $LAYERS.Keys) {
        $layerCfg = $LAYERS[$layerKey]
        $attrs = Invoke-LayerQuery $layerCfg.id $x $y $layerCfg.fields
        if (-not $attrs) { continue }

        foreach ($entry in $OUTPUT_COLUMNS) {
            if ($entry[0] -ne $layerKey) { continue }
            $field   = $entry[1]
            $colName = Get-OutputColName $entry
            $val     = $attrs.$field
            $result[$colName] = if ($null -eq $val) { "" } else { [string]$val }
        }
    }

    return $result
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

# Validate input file
if (-not (Test-Path $InputFile)) {
    Write-Error "Input file not found: $InputFile"
    exit 1
}

$rows = Import-Csv -Path $InputFile -Encoding UTF8

if ($rows.Count -eq 0) {
    Write-Error "Input CSV is empty or has no data rows."
    exit 1
}

$inputFields = $rows[0].PSObject.Properties.Name

# Resolve address column
$col = $AddressCol
if (-not $col) {
    foreach ($name in $inputFields) {
        if ($AUTO_DETECT_NAMES -contains $name.ToLower().Trim()) {
            $col = $name
            break
        }
    }
}
if (-not $col) {
    Write-Error "Could not auto-detect address column. Use -AddressCol to specify. Available: $($inputFields -join ', ')"
    exit 1
}
if ($inputFields -notcontains $col) {
    Write-Error "Column '$col' not found. Available: $($inputFields -join ', ')"
    exit 1
}

Write-Host "INFO  Using address column: '$col'" -ForegroundColor Cyan

# Build output field list
$outputCols = $OUTPUT_COLUMNS | ForEach-Object { Get-OutputColName $_ }
$allFields  = $inputFields + $outputCols

$results = [System.Collections.Generic.List[object]]::new()
$total   = $rows.Count

for ($i = 0; $i -lt $total; $i++) {
    $row     = $rows[$i]
    $address = $row.$col.Trim()
    Write-Host "INFO  [$($i+1)/$total] Looking up: $address" -ForegroundColor Cyan

    if (-not $address) {
        $lookup = [ordered]@{}
        foreach ($entry in $OUTPUT_COLUMNS) { $lookup[(Get-OutputColName $entry)] = "" }
        $lookup["geocoded_address"] = "SKIPPED (empty)"
    } else {
        $lookup = Invoke-AddressLookup $address
    }

    # Merge input row with lookup results into a flat ordered dict
    $outRow = [ordered]@{}
    foreach ($field in $inputFields) { $outRow[$field] = $row.$field }
    foreach ($key in $lookup.Keys)   { $outRow[$key]   = $lookup[$key] }

    $results.Add([PSCustomObject]$outRow)

    if ($Delay -gt 0 -and $i -lt ($total - 1)) {
        Start-Sleep -Milliseconds ([int]($Delay * 1000))
    }
}

# Export — force column order by selecting fields explicitly
$results | Select-Object $allFields | Export-Csv -Path $OutputFile -NoTypeInformation -Encoding UTF8

Write-Host "INFO  Done. Output written to: $OutputFile" -ForegroundColor Green
